server:
  port: 8080
  contextPath: /travelBuddy

spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate.ddl-auto: update
  database:
    driverClassName: com.mysql.jdbc.Driver

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/travelbuddy?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root1234

google:
  clientId: 390737871430-s7oklu3dh7kthlbcuffhvpodl5dsars4.apps.googleusercontent.com
  visionApi: https://vision.googleapis.com/v1/images:annotate

token:
  encryptionKey: E155A80E20A0E3D09BA3D775B5791B5494C2E08015EEE1E65DBD518E3DB05794
  expirationMinutes: 14400

analyzer:
  sentimentUrl: http://localhost:5000
